version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./njs/dist:/usr/local/nginx/njs
